# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [40]:
import numpy as np

2. Create a null vector of size 10 

In [41]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [42]:
arr1 = np.arange(10,49)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [43]:
arr1.shape

(39,)

5. Print the type of the previous array in question 3

In [44]:
type(arr1)

numpy.ndarray

6. Print the numpy version and the configuration


In [45]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hatee/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hatee/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hatee/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hatee/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hatee/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hatee/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hatee/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hatee/anaconda3\\Library\\include']
None


7. Print the dimension of the array in question 3


In [46]:
np.ndim(arr1)

1

8. Create a boolean array with all the True values

In [47]:
arr2 = np.ones(10, dtype = ("bool"))
arr2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [48]:
dim2 = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
print(dim2)
print("dimension " + str(np.ndim(dim2)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]
dimension 2


10. Create a three dimensional array



In [49]:
dim3 = np.random.randint(1,40,30).reshape(3,5,2)
print(dim3)
print("dimension " + str(np.ndim(dim3)))

[[[13 27]
  [17 27]
  [ 1 20]
  [ 9 15]
  [24 24]]

 [[35 26]
  [28 20]
  [35  3]
  [19  3]
  [30  5]]

 [[18 16]
  [ 9 36]
  [11 15]
  [38 35]
  [18  8]]]
dimension 3


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [50]:
reverse = arr1[::-1]
reverse

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [51]:
nullval = np.zeros(10)
nullval[4] = 1
nullval

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [52]:
imatrix = np.identity(3)
imatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [53]:
arr3 =  np.array([1, 2, 3, 4, 5], dtype = 'float64')
print(arr3)
print(arr3.dtype)

[1. 2. 3. 4. 5.]
float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [54]:
arr4 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr5 = np.array([[0., 4., 1.],[7., 2., 12.]])
multiply_arr = arr4*arr5
multiply_arr

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [55]:
arr6 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr7 = np.array([[0., 4., 1.],[7., 2., 12.]])
comp = arr6 < arr7
comp

array([[False,  True, False],
       [ True, False,  True]])

17. Extract all odd numbers from arr with values(0-9)

In [56]:
arr8 = np.arange(0,10)
arr8[arr8 %2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [57]:
arr8 = np.arange(0,10)
arr8[arr8 %2 == 1] = -1
arr8

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [58]:
arr9 = np.arange(10)
arr9[5:9] = 12
arr9

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [59]:
arr2d = np.ones((6,6))
arr2d

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [60]:
arr2d[1:-1,1:-1] = 0
arr2d

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [61]:
arr2dim = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2dim[1][1] = 12
arr2dim

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [62]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [63]:
dimen2 = np.arange(10).reshape(2,5)
dimen2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
dimen2[0]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [65]:
dimen2[1][1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [66]:
dimension2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
dimension2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
dimension2[:2,2:]

array([[3],
       [6]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [68]:
cross_array = np.random.randint(1,100,100).reshape(10,10)
cross_array

array([[54, 61, 38, 52, 33, 60, 49, 70, 95, 99],
       [18,  5, 20, 88, 18, 87, 12, 74, 10, 26],
       [53, 14, 69,  2, 18, 17, 46, 27, 63, 37],
       [69, 81, 38, 42, 47, 74,  9, 84, 95, 37],
       [69, 25, 97, 16, 13, 44, 31, 58, 49, 40],
       [ 7, 95, 27, 20, 29, 37, 23, 73, 99, 68],
       [74, 81, 49,  6, 32, 58, 94, 75, 38, 83],
       [98,  4, 46, 33, 25, 50, 72, 87, 79, 50],
       [24, 68, 10, 61, 20, 28, 19, 66, 50,  8],
       [26, 67, 49, 16, 82, 78, 68, 59, 35,  7]])

In [69]:
np.max(cross_array)

99

In [70]:
np.min(cross_array)

2

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [71]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
com_val = np.intersect1d(a,b)
com_val

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [72]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [73]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-0.11930791 -0.89570199 -0.5751979  -0.01096475]
 [ 2.53913076 -0.4581563   1.81388881  0.05149114]
 [-0.33482826 -0.43713451 -0.33474948  1.24420598]
 [ 0.63485815 -2.49029094  0.47478444 -1.30998925]
 [-0.02630134 -0.84215874  0.75915437  0.66983226]
 [ 0.04528092 -0.08865987 -1.38896287 -0.09584993]
 [ 0.85591408  0.61904782 -3.21246243 -0.26686355]]


In [74]:
data[np.where(names != 'Will')]

array([[-0.11930791, -0.89570199, -0.5751979 , -0.01096475],
       [ 2.53913076, -0.4581563 ,  1.81388881,  0.05149114],
       [ 0.63485815, -2.49029094,  0.47478444, -1.30998925],
       [ 0.04528092, -0.08865987, -1.38896287, -0.09584993],
       [ 0.85591408,  0.61904782, -3.21246243, -0.26686355]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [75]:
mask = (names != 'Will')&(names != 'Joe')
data[mask]

array([[-0.11930791, -0.89570199, -0.5751979 , -0.01096475],
       [ 0.63485815, -2.49029094,  0.47478444, -1.30998925]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [76]:
decimal_arr = np.arange(1.0,16).reshape(5,3)
decimal_arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

In [77]:
decimal_arr.dtype

dtype('float64')

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [78]:
decimal_arr2 = np.arange(1.0,17).reshape(2,2,4)
decimal_arr2

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

33. Swap axes of the array you created in Question 32

In [79]:
np.swapaxes(decimal_arr2,0,2)

array([[[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]],

       [[ 4., 12.],
        [ 8., 16.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [80]:
size_arr = np.random.randint(1,15,10)
size_arr

array([ 3,  7,  9,  9,  9,  4, 11,  2,  7,  6])

In [81]:
sqrt_arr = np.sqrt(size_arr)
sqrt_arr

array([1.73205081, 2.64575131, 3.        , 3.        , 3.        ,
       2.        , 3.31662479, 1.41421356, 2.64575131, 2.44948974])

In [82]:
sqrt_arr[np.where(size_arr<0.5)] = 0
sqrt_arr

array([1.73205081, 2.64575131, 3.        , 3.        , 3.        ,
       2.        , 3.31662479, 1.41421356, 2.64575131, 2.44948974])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [83]:
random_arr1 = np.random.randint(1,20,12)
random_arr2 = np.random.randint(1,30,12)
print(random_arr1)
print(random_arr2)

[14  4 17 10  7 13  4 16  9 12  1  3]
[ 9 11  9 19 22 27  2  7  3 19  8 17]


In [84]:
max_arr = np.maximum(random_arr1,random_arr2)
max_arr

array([14, 11, 17, 19, 22, 27,  4, 16,  9, 19,  8, 17])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [85]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [86]:
np.sort(names)

array(['Bob', 'Bob', 'Joe', 'Joe', 'Joe', 'Will', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [87]:
c = np.array([1,2,3,4,5]) 
d = np.array([5,6,7,8,9])
findindex = np.where(np.isin(c,d))
c = np.delete(c,findindex,None)
c

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [88]:
sampleArray = np.array([[34,43,73],
                           [82,22,12],
                           [53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [89]:
sampleArray = np.delete(sampleArray, 1, 1)
sampleArray

array([[34, 73],
       [82, 12],
       [53, 66]])

In [90]:
sampleArray = np.insert(sampleArray, 1, newColumn, axis = 1)
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [91]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [92]:
z = np.random.randint(1,20,20).reshape(4,5)
z

array([[ 2, 11,  5, 18, 17],
       [ 8,  4,  6, 12,  6],
       [12, 16, 18,  3,  1],
       [17, 17, 16,  6, 18]])

In [93]:
z.cumsum()

array([  2,  13,  18,  36,  53,  61,  65,  71,  83,  89, 101, 117, 135,
       138, 139, 156, 173, 189, 195, 213], dtype=int32)