# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np

In [8]:
arr1d = np.arange(0,10)
print("arrray 1D \n" + str(arr1d))
arr2d = arr1d.reshape(2,5)
print("arrray 2D \n" + str(arr2d))

arrray 1D 
[0 1 2 3 4 5 6 7 8 9]
arrray 2D 
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [17]:
arr1 = np.arange(0,10).reshape(2,5)
arr2 = np.ones(10).reshape(2,5)
arr2 = arr2.astype('int32')
print(arr1)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [19]:
np.vstack((arr1,arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [20]:
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [21]:
flat_arr = arr2d.ravel()
flat_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [22]:
arr_hd = np.arange(0,15).reshape(5,3)
arr_hd

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [23]:
arr_hd.ndim

2

In [84]:
arr_vec = arr_hd.flatten()
arr_vec

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [25]:
convert_arr = arr_vec.reshape(5,3)
convert_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [26]:
matrix1 = np.random.randint(1,30,25).reshape(5,5)
matrix1

array([[11, 18,  6,  1, 21],
       [19, 12, 11, 21, 10],
       [14, 15, 27, 18, 16],
       [20, 10, 22, 13, 19],
       [11,  9, 17, 21,  1]])

In [28]:
np.square(matrix1)

array([[121, 324,  36,   1, 441],
       [361, 144, 121, 441, 100],
       [196, 225, 729, 324, 256],
       [400, 100, 484, 169, 361],
       [121,  81, 289, 441,   1]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [29]:
matrix2 = np.random.randint(1,50,30).reshape(5,6)
matrix2

array([[39, 31, 32,  2, 45, 43],
       [46, 35, 24, 23, 46,  6],
       [ 6, 17, 18,  6, 21, 10],
       [20,  9,  2, 49, 18, 19],
       [30, 26, 15, 22,  1,  6]])

In [32]:
np.mean(matrix2)

22.233333333333334

## Question:9

### Find the standard deviation of the previous array in Q8?

In [46]:
np.std(matrix2)

14.458407780788159

## Question:10

### Find the median of the previous array in Q8?

In [47]:
np.median(matrix2)

20.5

## Question:11

### Find the transpose of the previous array in Q8?

In [48]:
np.transpose(matrix2)

array([[39, 46,  6, 20, 30],
       [31, 35, 17,  9, 26],
       [32, 24, 18,  2, 15],
       [ 2, 23,  6, 49, 22],
       [45, 46, 21, 18,  1],
       [43,  6, 10, 19,  6]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [49]:
diag_elm = np.random.randint(1,20,16).reshape(4,4)
diag_elm

array([[11,  1,  1,  4],
       [13, 17, 12, 14],
       [19, 16, 15, 19],
       [ 6, 18,  8, 18]])

In [51]:
diag = np.diagonal(diag_elm)
diag

array([11, 17, 15, 18])

In [52]:
diag_sum = np.trace(diag_elm)


61

## Question:13

### Find the determinant of the previous array in Q12?

In [55]:
from numpy.linalg import det
det(diag_elm) # first method
#np.linalg.det(diag_elm) # second method

6317.999999999991

## Question:14

### Find the 5th and 95th percentile of an array?

In [63]:
arr3 = np.array([3,6,10,34,56,33])
arr3

array([ 3,  6, 10, 34, 56, 33])

In [67]:
np.percentile(arr3,5)

3.75

In [68]:
np.percentile(arr3,95)

50.5

In [69]:
arr4 = np.array([[3,6,10,34,56,33],[5,7,17,45,53,66]]) 
arr4

array([[ 3,  6, 10, 34, 56, 33],
       [ 5,  7, 17, 45, 53, 66]])

In [71]:
np.percentile(arr4,25,axis = 1) # percentile of 2D array 

array([7. , 9.5])

In [72]:
np.percentile(arr4,25,axis = 0)

array([ 3.5 ,  6.25, 11.75, 36.75, 53.75, 41.25])

## Question:15

### How to find if a given array has any null values?

In [76]:
np.random.seed(123)
arr5 = np.random.randint(0,20,16).reshape(4,4)
arr5

array([[13,  2,  2,  6],
       [17, 19, 10,  1],
       [ 0, 17, 15,  9],
       [ 0, 14,  0, 15]])

In [81]:
null_val = arr5 == 0
null_val.any()

True

In [82]:
null_val.all()

False